"""add approval flows and client partner

Revision ID: b76d5290113f
Revises: 5abf7ed7f2f0
Create Date: 2026-03-07 12:59:30.885065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b76d5290113f'
down_revision = '5abf7ed7f2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('approver_type', sa.String(length=50), nullable=False),
    sa.Column('approver_target', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_flow_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'approval_flows', ['approval_flow_id'], ['id'])

    # Add client_partner to expenses if it doesn't exist
    # This is a bit manual because it was already added earlier in a failed migration
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='expenses' AND column_name='client_partner'"))
    if not res.fetchone():
        op.add_column('expenses', sa.Column('client_partner', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_step')
        batch_op.drop_column('approval_flow_id')

    op.drop_table('approval_decisions')
    op.drop_table('approval_steps')
    op.drop_table('approval_flows')
    # ### end Alembic commands ###
